language: python
cache: pip

python:
    - "3.6"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install Lektor
    - mkdir -p ../output
    - lektor build --output-path ../output
    - cp README* ../output
    - git rm -rf .
    - cp -r ../output/* .

script:
    - "echo 'no intermediate tasks!'"

after_success: |
    if [ -n "$LEKTOR_DEPLOY_PASSWORD" ]; then
      git checkout --orphan master
      git add *
      git -c user.name="D4G bot" -c user.email="No email" commit -am init
      git push --force https://$LEKTOR_DEPLOY_USERNAME:$LEKTOR_DEPLOY_PASSWORD@github.com/$TRAVIS_REPO_SLUG master
    fi


after_deploy:
    - "echo 'deployed!'"


